# -*- mode: ruby -*-
# vi: set ft=ruby :

# Provisioning script
provision_script = <<SCRIPT
#!/bin/bash
sudo echo "Hello there" > ~/hi.txt
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.provision :shell, :inline => provision_script

  config.vm.provider :vmpooler do |vmpooler|
    vmpooler.os = "centos-7-x86_64"
    #vmpooler.os = "ubuntu-1604-x86_64"
    vmpooler.ttl = 24
    vmpooler.password = "Qu@lity!"
  end
end
