# -*- mode: ruby -*-
# vi: set ft=ruby :

# Provisioning script
provision_script = <<SCRIPT
#!/bin/bash
echo "Hello there" > ~/hi.txt
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  # vagrant-vmpooler already assumes you are root
  config.vm.provision :shell, :inline => provision_script, privileged: false
  config.ssh.forward_agent = true

  config.vm.provider :vmpooler do |vmpooler|
    vmpooler.os = "centos-7-x86_64"
    #vmpooler.os = "ubuntu-1604-x86_64"
    vmpooler.ttl = 24
    vmpooler.password = "Qu@lity!"
  end
end
